name: Build
on: [push, pull_request, release]
jobs:
 build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
      with:
          persist-credentials: false

    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: nix build . -o site
deploy:
  provider: pages
  skip_cleanup: true
  github_token: ${{ secrets.GITHUB_TOKEN }}
  keep_history: true
  target_branch: master
  local_dir: site
  on:
    tags: true
