name: "Deploy"
on:
  pull_request:
  push:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: pages
env:
  TYPSITE_BIN_NAME: 'typsite-x86_64-unknown-linux-gnu'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: typst-community/setup-typst@v4
    - name: Setup Pages
      uses: actions/configure-pages@v4
    - uses: cachix/install-nix-action@v31
      with:
        install_url: https://releases.nixos.org/nix/nix-2.28.3/install
        extra_nix_config: |
          experimental-features = nix-command flakes pipe-operators
    - name: "Build Typsite"
      run: nix develop -c typsite c --config typsite
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./publish
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
